# These are supported funding model platforms

github: [PedroCavaleiro]
#patreon: # Replace with a single Patreon username
buy_me_a_coffee: PedroCavaleiro
custom: ["https://www.paypal.com/donate/?hosted_button_id=QJSXZMLT4NKJY"]
